İsTakipSistemiMVC/Models/Loglar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int logId { get; set; }
        public string logAciklama { get; set; }
        public string actionAd { get; set; }
        public string controllerAd { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> personelId { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}

İsTakipSistemiMVC/Controllers/SistemYoneticisiController.cs
using İsTakipSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using İsTakipSistemiMVC.Filters;

namespace İsTakipSistemiMVC.Controllers
{
    public class SistemYoneticisiController : Controller
    {
        İsTakipDBEntities entity = new İsTakipDBEntities();
        // GET: SistemYoneticisi
        [AuthFilter(1003)]
        // Chart 
        public ActionResult Index()
        {
            var birimler=(from b in entity.Birimler where b.aktiflik==true select b).ToList();

            string labelBirim = "[";
            foreach (var birim in birimler)
            {
                labelBirim += "'" + birim.birimAd + "',";
            }

            labelBirim += "]";

            ViewBag.labelBirim = labelBirim;

            List<int> islerToplam=new List<int>();

            foreach (var birim in birimler)
            {
                int toplam = 0;

                var personeller = (from p in entity.Personeller where p.personelBirimId==birim.birimId && p.aktiflik==true select p).ToList();

                foreach (var personel in personeller)
                {
                    var isler = (from i in entity.Isler where i.isPersonelId == personel.PersonelId select i).ToList();

                    toplam += isler.Count();
                }
                islerToplam.Add(toplam);
            }
            // AKTİF VERİLERİ GÖRMEK İÇİN Chart kodlar sayesinde Yönetici hesabı ile görüyoruz
            string dataIs = "[";

            foreach(var i in islerToplam)
            {
                dataIs += "'" + i + "',";
            }
            dataIs += "]";

            ViewBag.dataIs = dataIs;

           return View();
        }

        public ActionResult Birim()
        {
            // index içerisinde de yetki tür bilgisine göre kotrol sağlıyoruz. sadece yetki tür ıd si 1003 olanlarının görmesini istiyoruz
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);

            if (yetkiTurId == 1003)
            {
                var birimler=(from b in entity.Birimler where b.aktiflik==true select b).ToList();
                return View(birimler);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            } 

        }

        public ActionResult Olustur()
        {
            // index içerisinde de yetki tür bilgisine göre kotrol sağlıyoruz. sadece yetki tür ıd si 1003 olanlarının görmesini istiyoruz
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);

            if (yetkiTurId == 1003)
            {
                
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [HttpPost,ActFilter("Yeni Birim Eklendi")]
        public ActionResult Olustur(string birimAd)
        {
            Birimler yeniBirim = new Birimler();
            // using System.Globalization;  en yukarıya bu kodu ve burayada string yeniAd Culturainfo verdiğimiz için EKLE'nilen yeniAd'lar baş harfleri BÜYÜMESİNİ sağlıyoruz.
            string yeniAd =CultureInfo.CurrentCulture.TextInfo.ToTitleCase(birimAd);
            yeniBirim.birimAd = yeniAd;
            yeniBirim.aktiflik = true;

            entity.Birimler.Add(yeniBirim);
            entity.SaveChanges();

            TempData["bilgi"] = yeniBirim.birimAd;

            return RedirectToAction("Birim");

        }

        public ActionResult Guncelle(int id)
        {
            // index içerisinde de yetki tür bilgisine göre kotrol sağlıyoruz. sadece yetki tür ıd si 1003 olanlarının görmesini istiyoruz
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);

            if (yetkiTurId == 1003)
            {
                var birim=(from b in entity.Birimler where b.birimId==id select b).FirstOrDefault();

                return View(birim);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }
        [HttpPost,ActFilter("Birim Güncellendi")]
        public ActionResult Guncelle(FormCollection fc)
        {
            int birimId = Convert.ToInt32(fc["birimId"]);
            string yeniAd = fc["birimAd"];
            var birim = (from b in entity.Birimler where b.birimId == birimId select b).FirstOrDefault();
            birim.birimAd=CultureInfo.CurrentCulture.TextInfo.ToTitleCase(yeniAd);
            entity.SaveChanges();

            TempData["bilgi"]=birim.birimAd;

            return RedirectToAction("Birim");

        }
        [ActFilter("Birim Silindi")]
        // parametre olarak int id veriyoruz
        public ActionResult Sil(int id)
        {
            // index içerisinde de yetki tür bilgisine göre kotrol sağlıyoruz. sadece yetki tür ıd si 1003 olanlarının görmesini istiyoruz
            int yetkiTurId = Convert.ToInt32(Session["PersonelYetkiTurId"]);

            if (yetkiTurId == 1003)
            {
                var birim = (from b in entity.Birimler where b.birimId == id select b).FirstOrDefault();
                // Remove silmek için kullanılır.
                // entity.SaveChanges ile de veri tabanına bu işlemi gönderiyoruz.
                birim.aktiflik = false;
                entity.SaveChanges();

                TempData["bilgi"] = birim.birimAd;

                return RedirectToAction("Birim");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        [AuthFilter(1003)]
        public ActionResult Loglar()
        {
            var loglar = (from l in entity.Loglar orderby l.tarih descending select l).ToList();
            return View(loglar);
        }
    }
}

İsTakipSistemiMVC/Views/SistemYoneticisi/Birim.cshtml
@model IEnumerable<İsTakipSistemiMVC.Models.Birimler>


@{
    ViewBag.Title = "Birim";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}

<p class="mt-5">
    @Html.ActionLink("Yeni Birim Ekle","Olustur",new {},new {@class="btn btn-primary"})
</p>

<table class="table table-bordered table-striped table-dark">
    <tr class="text-center">
        <th>
            <!-- DisplayNameFor method'unu kullanıyoruz direk modelden birimAdı getirmesini sağlıyoruz.  DisplayFor içeriği getirmeye yarıyor.-->
            @Html.DisplayNameFor(model => model.birimAd)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="text-center">
            <td>@Html.DisplayFor(modelItem => item.birimAd)</td>
            <td>
                <!-- burada güncelle butonunu oluşturuyoruz.-->
                @Html.ActionLink("Güncelle", "Guncelle", new { id = item.birimId }, new { @class = "btn btn-success" })
            </td>
            <td>
                <!-- burada güncelle butonunu oluşturuyoruz.-->
                @Html.ActionLink("Sil", "Sil", new { id = item.birimId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>

İsTakipSistemiMVC/Views/SistemYoneticisi/Guncelle.cshtml
@model İsTakipSistemiMVC.Models.Birimler



@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}

<div class="container mt-5">
    <h3>Birim Güncelleme İşlemi</h3>
    <hr />
    @using (Html.BeginForm("Guncelle", "SistemYoneticisi", FormMethod.Post))
    {
        @Html.HiddenFor(model=>model.birimId)
        <div class="row mb-3">
            <!-- Labelfor üzerinde yazması gereken yazıyı belirtecek 
                htmlAttiributes okunabilirliği için daha düzgün bir kullanım gerçekleştiriyoruz.
                -->
            @Html.LabelFor(model=>model.birimAd, htmlAttributes: new {@class="col-sm-3 coll-form-label"})
            <div class="col-sm-6">
                <!-- input için de editorfor kullanıyoruz.
                    burada value ayarlamadık model.birimAd diyerek editorFor'a hem nameyi hemde value birimAd'ın içeriği yaptık-->
                @Html.EditorFor(model => model.birimAd, new {htmlAttributes=new {@class="form-control"}})
            </div>
        </div>
        <div class="text-center d-grid gap-5 col-6 mx-auto">
            <button class="btn btn-success" type="submit">GÜNCELLE</button>
        </div>
    }
</div>

İsTakipSistemiMVC/Views/SistemYoneticisi/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}


<script src="~/Scripts/chart.min.js"></script>


<div class="mt-5">
    <canvas id="myChart" width="10" height="5"></canvas>
</div>


<script>
    const ctx = document.getElementById('myChart').getContext('2d');

    const mychart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(ViewBag.labelBirim),
            datasets: [{
                label: 'Birimlerin Toplam İşleri',
                data: @Html.Raw(ViewBag.dataIs),
                backgroundColor: [
                    '#22333b'
                ],
                borderColor: [
                    '#0a0908'
                ],
                borderWidth:2
            }]
        }
    })

</script>

İsTakipSistemiMVC/Views/SistemYoneticisi/Loglar.cshtml
@model IEnumerable<İsTakipSistemiMVC.Models.Loglar>
@using GridMvc.Html


@{
    ViewBag.Title = "Loglar";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}

<div class="container mt-5">
    @Html.Grid(Model).Columns(column =>
{
    column.Add(m => m.Personeller.PersonelAdSoyad).Titled("Personel Ad Soyad").Filterable(true); 
    column.Add(m => m.logAciklama).Titled("Açıklama");
    column.Add(m => m.actionAd).Titled("Action Adı");
    column.Add(m => m.controllerAd).Titled("Controller Adı");
    column.Add(m => m.tarih).Titled("Tarih").Sortable(true);
}).WithPaging(3)
</div>

İsTakipSistemiMVC/Views/SistemYoneticisi/Olustur.cshtml
@{
    ViewBag.Title = "Olustur";
    Layout = "~/Views/Shared/_LayoutSistemYoneticisi.cshtml";
}

<div class="container mt-5">
    <h3>Yeni Birim Ekleme İşlemi</h3>
    <hr />
    <!-- Form oluşturuyoruz ve bu form'un içerisinde birimAdı ve ekle butonu yazsın'-->
    <!-- yazı yazıp EKLE butonuna tıkladığımızda Olustur methoduna Post işlemi gerçekleştirilecek-->
    @using (Html.BeginForm("Olustur", "SistemYoneticisi", FormMethod.Post)) 
    {
        <div class="row mb-3">
            <label for="birimAd" class="col-sm-3 col-form-label">Birim Adı:</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="birimAd" name="birimAd" />
            </div>
        </div>
        <div class="text-center d-grid gap-5 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">EKLE</button>
        </div>
    }
</div>