İsTakipSistemiMVC/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace İsTakipSistemiMVC.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        // kullanıcı giriş yapma sayfası olan "Login" controller'ının "Index" action'ına yönlendirilir.
        public ActionResult Index()
        {
            // çıkış yapabilmesi için sesionların boşaltılması gerekiyor. bu yüzden session.Abandon yazıyoru.
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
    }
}

İsTakipSistemiMVC/Controllers/PersonelController.cs
using İsTakipSistemiMVC.Filters;
using İsTakipSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace İsTakipSistemiMVC.Controllers
{
    public class PersonelController : Controller
    {
        İsTakipDBEntities entity = new İsTakipDBEntities();

        [AuthFilter(1003)]
        public ActionResult Index()
        {
            var personeller = (from p in entity.Personeller where p.personelYetkiTurId != 1003 && p.aktiflik == true select p).ToList();
            return View(personeller);
        }

        [AuthFilter(1003)]
        public ActionResult Olustur()
        {
            BirimYetkiTurler by = birimYetkiTurlerDoldur();

            ViewBag.mesaj = null;
            return View(by);


        }
        [HttpPost, ActFilter("Yeni Personel Eklendi")]
        public ActionResult Olustur(FormCollection fc)
        {
            string personelKullaniciAd = fc["kullaniciAd"];
            var personel = (from p in entity.Personeller where p.personelKullanıcıAd == personelKullaniciAd select p).FirstOrDefault();

            int birimId = Convert.ToInt32(fc["birim"]);
            if (Convert.ToInt32(fc["yetkiTur"]) == 1)
            {
                var birimYoneticiKontrol = (from p in entity.Personeller where p.personelBirimId == birimId && p.personelYetkiTurId == 1 select p).FirstOrDefault();
                if (birimYoneticiKontrol != null)
                {
                    BirimYetkiTurler by = birimYetkiTurlerDoldur();

                    ViewBag.mesaj = "Bu birimin sadece bir yöneticisi olabilir";
                    TempData["bilgi"] = null;
                    return View(by);
                }
            }

            if (personel == null)
            {
                Personeller yeniPersonel = new Personeller();

                yeniPersonel.PersonelAdSoyad = fc["adSoyad"];
                yeniPersonel.personelKullanıcıAd = personelKullaniciAd;
                yeniPersonel.PersonelParola = fc["parola"];
                yeniPersonel.personelBirimId = Convert.ToInt32(fc["birim"]);
                yeniPersonel.personelYetkiTurId = Convert.ToInt32(fc["yetkiTur"]);
                yeniPersonel.yeniPersonel = true;
                yeniPersonel.aktiflik = true;

                entity.Personeller.Add(yeniPersonel);
                entity.SaveChanges();
                TempData["bilgi"] = yeniPersonel.personelKullanıcıAd;
                return RedirectToAction("Index");
            }
            else
            {
                BirimYetkiTurler by = birimYetkiTurlerDoldur();

                ViewBag.mesaj = "Kullanıcı Adı Bulunmaktadır";
                TempData["bilgi"] = null;
                return View(by);
            }
        }


        [AuthFilter(1003)]
        public ActionResult Guncelle(int id)
        {
            var personel = (from p in entity.Personeller where p.PersonelId == id select p).FirstOrDefault();

            return View(personel);
        }
        [HttpPost, ActFilter("Personel Güncellendi")]
        public ActionResult Guncelle(int id, string adSoyad)
        {
            Personeller personel = (from p in entity.Personeller where p.PersonelId == id select p).FirstOrDefault();
            personel.PersonelAdSoyad = adSoyad;

            entity.SaveChanges();
            TempData["bilgi"] = personel.personelKullanıcıAd;

            return RedirectToAction("Index");
        }

        [AuthFilter(1003)]
        public ActionResult Sil(int id)
        {
            Personeller personel = (from p in entity.Personeller where p.PersonelId == id select p).FirstOrDefault();
            return View(personel);
        }

        [HttpPost, ActFilter("Personel Silindi")]
        public ActionResult Sil(FormCollection fc)
        {
            int personelId = Convert.ToInt32(fc["PersonelId"]);
            var personel = (from p in entity.Personeller where p.PersonelId == personelId select p).FirstOrDefault();
            personel.aktiflik = false;
            entity.SaveChanges();

            TempData["bilgi"] = personel.personelKullanıcıAd;
            return RedirectToAction("Index");
        }


        public BirimYetkiTurler birimYetkiTurlerDoldur()
        {
            BirimYetkiTurler by = new BirimYetkiTurler();

            by.birimlerList = (from b in entity.Birimler where b.aktiflik == true select b).ToList();
            by.yetkiTurlerList = (from y in entity.YetkiTurler where y.yetkiTurId != 1003 select y).ToList();

            return by;
        }
    }
}

İsTakipSistemiMVC/Controllers/SifreKontrolController.cs
using İsTakipSistemiMVC.Filters;
using İsTakipSistemiMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace İsTakipSistemiMVC.Controllers
{
    public class SifreKontrolController : Controller
    {
        İsTakipDBEntities entity = new İsTakipDBEntities();
        // GET: SifreKontrol
        public ActionResult Index()
        {
            // LoginControllerden Session["PersonelId"] alıp giriş yapan kullanıcının personelId sini yakalamak için.
            int personelId = Convert.ToInt32(Session["PersonelId"]);

            if (personelId == 0) return RedirectToAction("Index", "Login");

            var personel = (from p in entity.Personeller where p.PersonelId == personelId select p).FirstOrDefault();
            //  ilk açıldığında görünmemesi için null veriyoruz.
            ViewBag.mesaj = null;
            ViewBag.yetkiTurId = null;
            ViewBag.sitil = null;


            return View(personel);
        }

        [HttpPost, ActFilter("Parola Değiştirildi")]
        public ActionResult Index(int personelId, string eskiParola, string yeniParola, string yeniParolaKontrol)
        {
            var personel = (from p in entity.Personeller where p.PersonelId == personelId select p).FirstOrDefault();

            if (eskiParola != personel.PersonelParola)
            {
                ViewBag.mesaj = "Eski parolanızı yanlış girdiniz";
                ViewBag.sitil = "alert alert-danger";

                return View(personel);
            }

            if (yeniParola != yeniParolaKontrol)
            {
                ViewBag.mesaj = "Yeni parola ve yeni parola tekrarı tekrarı eşleşmedi";
                ViewBag.sitil = "alert alert-danger";

                return View(personel);
            }

            if (yeniParola.Length < 6 || yeniParola.Length > 15)
            {
                ViewBag.mesaj = "Yeni parola en az 6 karakter en çok 15 karakter olmalıdır";
                ViewBag.sitil = "alert alert-danger";

                return View(personel); 
            }

            personel.PersonelParola = yeniParola;
            personel.yeniPersonel = false;
            entity.SaveChanges();

            TempData["bilgi"] = personel.personelKullanıcıAd;

            ViewBag.mesaj = "Parolanız başarıyla değiştirildi. Anasayfaya yönlendiriliyorsunuz.";
            ViewBag.sitil = "alert alert-success";
            ViewBag.yetkiTurId = personel.personelYetkiTurId;

            return View(personel);
        }
    }
}

İsTakipSistemiMVC/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

İsTakipSistemiMVC/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager mt-5">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="page-item active"><span class="page-link">@i</span></li>
            }
            else
            {
            <li class="page-item"><a a class="page-link" href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li class="page-item"><a class="page-link" href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

İsTakipSistemiMVC/Views/Shared/_LayoutCalisan.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>İş Takip Çalışan</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>


</head>
<body>
    <nav class="navbar navbar-expand-md bg-body-secondary">
        <div class="container">
            <a class="navbar-brand" href="#">İş Takip Çalışan</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Calisan", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Tamamla", "Yap", "Calisan", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Takip", "Takip", "Calisan", new { }, new { @class = "nav-link" })
                    </li>

                </ul>
                <!-- Çıkış butonu oluşturuyoruz.-->
                <!-- boş bir new {} oluşturup buton olmasını sağlıyoruz.-->
                <!-- tıklandığında logout daki index e gidecek-->
                <div class="d-flex nav-item">
                    @Html.ActionLink("Parola Değiştir", "Index", "SifreKontrol", new { }, new { @class = "btn btn-light mx-2" })
                    @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        <!-- değişken sayfalar olacak bunu renderbody etiketi ile cağıraçağız  -->
        @RenderBody()

    </main>
</body>
</html>

İsTakipSistemiMVC/Views/Shared/_LayoutSistemYoneticisi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>İş Takip Admin Sistem Yöneticisi</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/gridmvc.js"></script>
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />



</head>
<body>
    <nav class="navbar navbar-expand-md bg-body-secondary">
        <div class="container">
            <a class="navbar-brand" href="#">İş Takip Sistem Yöneticisi</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- 1. boşluk ekranda yazan -->
                    <!-- 2. boşluk Action tektikleniyor gerçekleştiriyoruz. -->
                    <!-- 3. boşluk controller oluşturup buradaki 2. boşluğa yönlendiriyoruz.-->
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "SistemYoneticisi", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Birim İşlemleri", "Birim", "SistemYoneticisi", new { }, new { @class = "nav-link" })
                    </li>
                    @Html.ActionLink("Personel İşlemleri", "Index", "Personel", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Log İşlemleri", "Loglar", "SistemYoneticisi", new { }, new { @class = "nav-link" })
                    </li>


                </ul>
                <!-- Çıkış butonu oluşturuyoruz.-->
                <!-- boş bir new {} oluşturup buton olmasını sağlıyoruz.-->
                <!-- tıklandığında logout daki index e gidecek-->
                <div class="d-flex nav-item">
                    @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        <!-- değişken sayfalar olacak bunu renderbody etiketi ile cağıraçağız  -->
        @RenderBody()

    </main>
</body>
</html>

İsTakipSistemiMVC/Views/Shared/_LayoutYonetici.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>İş Takip Admin Yönetici</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>


</head>
<body>
    <nav class="navbar navbar-expand-md bg-body-secondary">
        <div class="container">
            <a class="navbar-brand" href="#">İş Takip Yönetici</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <!-- 1. boşluk ekranda yazan -->
                    <!-- 2. boşluk Action tektikleniyor gerçekleştiriyoruz. -->
                    <!-- 3. boşluk controller oluşturup buradaki 2. boşluğa yönlendiriyoruz.-->
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Ata", "Ata", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İş Takip", "Takip", "Yonetici", new { }, new { @class = "nav-link" })
                    </li>

                </ul>
                <!-- Çıkış butonu oluşturuyoruz.-->
                <!-- boş bir new {} oluşturup buton olmasını sağlıyoruz.-->
                <!-- tıklandığında logout daki index e gidecek-->
                <div class="d-flex nav-item">
                    @Html.ActionLink("Parola Değiştir", "Index", "SifreKontrol", new { }, new {@class="btn btn-light mx-2"})
                    @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        <!-- değişken sayfalar olacak bunu renderbody etiketi ile cağıraçağız  -->
        @RenderBody()

    </main>
</body>
</html>

İsTakipSistemiMVC/Views/Shared/_PartialAylarSelect.cshtml
<!-- Ayları listeletiyoruz.-->
<select class="form-select" name="aylar">
    <option value="01">Ocak</option>
    <option value="02">Şubat</option>
    <option value="03">Mart</option>
    <option value="04">Nisan</option>
    <option value="05">Mayıs</option>
    <option value="06">Haziran</option>
    <option value="07">Temmuz</option>
    <option value="08">Ağustos</option>
    <option value="09">Eylül</option>
    <option value="10">Ekim</option>
    <option value="11">Kasım</option>
    <option value="12">Aralık</option>
</select>